name: Build MultiKickViewer APKs & AAB

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up JDK 11
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '11'

    - name: Ensure gradlew exists
      run: |
        if [ ! -f "./gradlew" ]; then
          echo "gradlew não encontrado, criando wrapper..."
          gradle wrapper
        fi
        chmod +x ./gradlew

    - name: Build Debug, Release APKs & AAB
      run: |
        ./gradlew assembleDebug assembleRelease bundleRelease

    - name: Upload Debug APK
      uses: actions/upload-artifact@v4
      with:
        name: MultiKickViewer-APK-Debug
        path: app/build/outputs/apk/debug/app-debug.apk

    - name: Upload Release APK
      uses: actions/upload-artifact@v4
      with:
        name: MultiKickViewer-APK-Release
        path: app/build/outputs/apk/release/app-release.apk

    - name: Upload Release AAB
      uses: actions/upload-artifact@v4
      with:
        name: MultiKickViewer-AAB-Release
        path: app/build/outputs/bundle/release/app-release.aab
        
